steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/devops-tp1/demo-repository/wp-db:0.2', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/devops-tp1/demo-repository/wp-db:0.2']

images:
  - 'us-central1-docker.pkg.dev/devops-tp1/demo-repository/wp-db:0.2'
